version: "3.7"

services:
  db:
    image: postgres
    container_name: rentapidb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: rentapi
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: rentapi
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app

volumes:
  pgdata:
    driver: local